######################################################################
# Automatically generated by qmake (2.01a) ?? 12? 12 16:49:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
